[symlinks]
# Source (in repo) -> Target (on system)
"config/nvim" = "~/.config/nvim"
"config/starship.toml" = "~/.config/starship.toml"
"config/ghostty/config" = "~/.config/ghostty/config"
".zshrc" = "~/.zshrc"
".vimrc" = "~/.vimrc"
